parameters:
#    jac_about_us.example.class: Jac\AboutUsBundle\Example

services:
#    jac_about_us.example:
#        class: %jac_about_us.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
