jac_home_homepage:
    pattern:  /{_locale}
    defaults: { _controller: JacHomeBundle:Default:index, _locale: es }
    requirements:
      _locale: en|es

jac_home_privacy_notice:
    pattern: /{_locale}/privacy-notice
    defaults: { _controller: JacHomeBundle:Default:privacyNotice, _locale: es }
    requirements:
      _locale: en|es
