parameters:
#    jac_home.example.class: Jac\HomeBundle\Example

services:
#    jac_home.example:
#        class: %jac_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
